# Generated by Django 3.1.2 on 2020-10-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenatixTask', '0003_auto_20201031_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
