# Generated by Django 3.1.2 on 2020-10-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenatixTask', '0004_auto_20201031_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.IntegerField(choices=[(1, 'kg'), (2, 'liter')], default=None),
        ),
    ]
