# Generated by Django 3.1.2 on 2020-10-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenatixTask', '0006_auto_20201031_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(),
        ),
    ]
