# Generated by Django 3.1.2 on 2020-10-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zenatixTask', '0008_auto_20201031_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(to='zenatixTask.Ingredient'),
        ),
    ]
